version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    build:
      context: ./keycloak
      dockerfile: ./Dockerfile
      args:
        STOREPASS: "TMP_PASSWORD"
    depends_on:
      - db
    environment:
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "secret"

      KC_FEATURES: "preview"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_CACHE_CONFIG_FILE: "cache-ispn-jdbc-ping.xml"

      KC_HOSTNAME: "localhost"
      KC_HOSTNAME_STRICT: "true"
      KC_HOSTNAME_STRICT_HTTPS: "true"

      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "TEMP_PASSWORD"
      STOREPASS: "TMP_PASSWORD"
    expose:
      - "8080"
      - "8443"
      - "7800"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./tls.crt:/etc/nginx/certs/tls.crt:ro
      - ./tls.key:/etc/nginx/certs/tls.key:ro
    depends_on:
      - keycloak
    ports:
      - "80:80"
      - "443:443"
volumes:
  keycloak-db:
